---
- name: Ensure tftp directory for pxe exists
  file:
    path: "{{ tftp_root_directory }}"
    state: directory
    owner: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    mode: "{{ tftp_mode }}"
  tags:
    - tftp

- name: Ensure pxelinux.cfg directory exists
  file:
    path: "{{ tftp_root_directory }}/pxelinux.cfg"
    state: directory
    owner: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    mode: "{{ tftp_mode }}"
  tags:
    - tftp

- name: Copy pxelinux.0 to tftp root dir
  copy:
    src: "/usr/lib/PXELINUX/pxelinux.0"
    dest: "{{ tftp_root_directory }}"
    remote_src: true
    mode: 0644
  tags:
    - tftp

- name: Download RHCOS Iso
  get_url:
    url: "{{ openshift_mirror_url }}/{{ coreos_iso }}"
    dest: "/tmp/rhcos.iso"
    mode: 0644
  tags:
    - tftp

- name: Extract efiboot.img
  iso_extract:
    image: /tmp/rhcos.iso
    dest: /tmp
    files:
      - images/efiboot.img

- name: Mount efiboot.img
  shell: "mount efiboot.img /media"
  args:
    chdir: /tmp
    executable: /bin/bash
  changed_when: false
  ignore_errors: True

- name: Copy BOOTX64.efi and grubx64.efi to tftp root dir
  copy:
    src: "/media/{{ item }}"
    dest: "{{ tftp_root_directory }}"
    remote_src: true
    mode: 0555
  with_items:
    - EFI/redhat/grubx64.efi
    - EFI/BOOT/BOOTX64.EFI
  tags:
    - tftp

- name: Copy ldlinux.c32 to tftp root dir
  copy:
    src: "/usr/lib/syslinux/modules/bios/ldlinux.c32"
    dest: "{{ tftp_root_directory }}"
    remote_src: true
    mode: 0644
  tags:
    - tftp

- name: Copy menu.c32 to tftp root dir
  copy:
    src: "/usr/lib/syslinux/modules/bios/menu.c32"
    dest: "{{ tftp_root_directory }}"
    remote_src: true
    mode: 0644
  tags:
    - tftp

- name: Copy libmenu.c32 to tftp root dir
  copy:
    src: "/usr/lib/syslinux/modules/bios/libmenu.c32"
    dest: "{{ tftp_root_directory }}"
    remote_src: true
    mode: 0644
  tags:
    - tftp

- name: Copy libutil.c32 to tftp root dir
  copy:
    src: "/usr/lib/syslinux/modules/bios/libutil.c32"
    dest: "{{ tftp_root_directory }}"
    remote_src: true
    mode: 0644
  tags:
    - tftp

- name: Ensure service is started
  service:
    name: "{{ tftp_service }}"
    state: started
    enabled: true
  tags:
    - tftp

- name: Generate grub.cfg for master
  template:
    src: "grub.cfg.j2"
    dest: "{{ tftp_root_directory }}/grub.cfg-01-{{ item | replace(':', '-') }}"
    owner: root
    group: "root"
    mode: 0644
  with_items:
    - "{{ master }}"
  vars:
    fallback: master
  tags:
    - tftp

- name: Generate grub.cfg for worker
  template:
    src: "grub.cfg.j2"
    dest: "{{ tftp_root_directory }}/grub.cfg-01-{{ item | replace(':', '-') }}"
    owner: root
    group: "root"
    mode: 0644
  with_items:
    - "{{ worker }}"
  vars:
    fallback: worker
  tags:
    - tftp

- name: Generate grub.cfg for bootstrap
  template:
    src: "grub.cfg.j2"
    dest: "{{ tftp_root_directory }}/grub.cfg-01-{{ item | replace(':', '-') }}"
    owner: root
    group: "root"
    mode: 0644
  with_items:
    - "{{ bootstrap }}"
  vars:
    fallback: bootstrap
  tags:
    - tftp

- name: Generate pxelinux.cfg for bootstrap
  template:
    src: "pxelinux.cfg.j2"
    dest: "{{ tftp_root_directory }}/pxelinux.cfg/01-{{ item | replace(':', '-') }}"
    owner: root
    group: "root"
    mode: 0644
  with_items:
    - "{{ bootstrap }}"
  vars:
    default: bootstrap
  tags:
    - tftp

- name: Generate pxelinux.cfg for master
  template:
    src: "pxelinux.cfg.j2"
    dest: "{{ tftp_root_directory }}/pxelinux.cfg/01-{{ item | replace(':', '-') }}"
    owner: root
    group: "root"
    mode: 0644
  with_items:
    - "{{ master }}"
  vars:
    default: master
  tags:
    - tftp

- name: Generate pxelinux.cfg for worker
  template:
    src: "pxelinux.cfg.j2"
    dest: "{{ tftp_root_directory }}/pxelinux.cfg/01-{{ item | replace(':', '-') }}"
    owner: root
    group: "root"
    mode: 0644
  with_items:
    - "{{ worker }}"
  vars:
    default: worker
  tags:
    - tftp

- name: Generate default pxelinux.cfg
  template:
    src: "pxelinux.cfg.j2"
    dest: "{{ tftp_root_directory }}/pxelinux.cfg/default"
    owner: root
    group: "root"
    mode: 0644
  vars:
    default: default
  tags:
    - tftp

- name: Download Kernel
  get_url:
    url: "{{ openshift_mirror_url }}/{{ linuxefi }}"
    dest: "{{ tftp_root_directory }}"
    mode: 0644
  tags:
    - tftp

- name: Download Initramfs
  get_url:
    url: "{{ openshift_mirror_url }}/{{ initrdefi }}"
    dest: "{{ tftp_root_directory }}"
    mode: 0644
  tags:
    - tftp

...
