---

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - tftp
    - nginx

- name: Update cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - tftp
    - nginx

- name: Apt install packages
  apt:
    name:
      - p7zip-full
      - rpm2cpio
      - cpio
      - syslinux-common
      - pxelinux
      - grub-efi-amd64-signed
      - shim-signed
    state: present
    update_cache: true
  tags:
    - tftp
    - nginx

- name: Configure NGINX-Server for PXE boot
  include_tasks: configure_nginx.yml
  tags:
    - nginx

- name: Configure TFTP-Server for PXE boot
  include_tasks: configure_tftp.yml
  tags:
    - tftp

- name: wait for rootfs download
  async_status:
    jid: "{{ download_rootfs_nginx.ansible_job_id }}"
  register: res_rootfs
  until: res_rootfs.finished
  retries: 100
  delay: 10
  tags:
    - nginx

- name: wait for coroes iamge download
  async_status:
    jid: "{{ download_coreos_image_nginx.ansible_job_id }}"
  register: res_image
  until: res_image.finished
  retries: 100
  delay: 10
  tags:
    - nginx
...
