---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Apt install packages
      apt:
        name: 
          - tftpd-hpa
          - nginx
          - p7zip-full
        state: present
        update_cache: yes
      tags:
        - working
    - name: Start service tftpd-hpa
      service:
        name: tftpd-hpa
        state: started
      tags:
        - working
    - name: Start service nginx
      service:
        name: nginx
        state: started
      tags:
        - working

  tasks:
    - name: Include pxe
      include_role:
        name: 'gepaplexx.pxe'
      vars:
        nginx_pxe_directory: /var/www/pxe
        tftp_root_directory: /srv/tftp/pxelinux

        # openshift_mirror_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/latest
        coreos_root_fs: rhcos-live-rootfs.x86_64.img
        coreos_image: rhcos-metal.x86_64.raw.gz
        linuxefi: rhcos-live-kernel-x86_64
        initrdefi: rhcos-live-initramfs.x86_64.img

        mac_prefix: '00:11:22:33:44'
        bootstrap:
          - "{{ mac_prefix }}:01"

        master:
          - "{{ mac_prefix }}:02"
          - "{{ mac_prefix }}:03"

        worker:
          - "{{ mac_prefix }}:04"
          - "{{ mac_prefix }}:05"
          - "{{ mac_prefix }}:06"
          - "{{ mac_prefix }}:07"
          - "{{ mac_prefix }}:08"
          - "{{ mac_prefix }}:09"
          - "{{ mac_prefix }}:0a"
          - "{{ mac_prefix }}:0b"
          - "{{ mac_prefix }}:0c"
          - "{{ mac_prefix }}:0d"
          - "{{ mac_prefix }}:0e"
          - "{{ mac_prefix }}:0f"
          - "{{ mac_prefix }}:10"
          - "{{ mac_prefix }}:11"
          - "{{ mac_prefix }}:12"
          - "{{ mac_prefix }}:13"
          - "{{ mac_prefix }}:14"
          - "{{ mac_prefix }}:15"
          - "{{ mac_prefix }}:1a"
          - "{{ mac_prefix }}:1b"
          - "{{ mac_prefix }}:1c"
          - "{{ mac_prefix }}:1d"
          - "{{ mac_prefix }}:1e"
          - "{{ mac_prefix }}:1f"
          - "{{ mac_prefix }}:20"
          - "{{ mac_prefix }}:21"
          - "{{ mac_prefix }}:22"
          - "{{ mac_prefix }}:23"
          - "{{ mac_prefix }}:24"
          - "{{ mac_prefix }}:25"
          - "{{ mac_prefix }}:26"
          - "{{ mac_prefix }}:27"
          - "{{ mac_prefix }}:28"
          - "{{ mac_prefix }}:29"
          - "{{ mac_prefix }}:2a"
          - "{{ mac_prefix }}:2b"
          - "{{ mac_prefix }}:2c"
          - "{{ mac_prefix }}:2d"

        nginx_host_port: 10.20.26.12:8080
...
