---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Apt install packages
      apt:
        name: 
          - tftpd-hpa
          - nginx
          - p7zip-full
        state: present
        update_cache: yes
      tags:
        - working
    - name: Start service tftpd-hpa
      service:
        name: tftpd-hpa
        state: started
      tags:
        - working
    - name: Start service nginx
      service:
        name: nginx
        state: started
      tags:
        - working

  tasks:
    - name: Include pxe
      include_role:
        name: 'gepaplexx.pxe'
      vars:
        openshift_mirror_url: https://docs.google.com/
        linuxefi: uc?export=download&id=1UuTeNa8rZPorwOB-pC67BH7rSIQhGDf-
        initrdefi: uc?export=download&id=1UfeFs-feOdsyIH8_n8TwrdHUNnJvhyeB
        coreos_root_fs: uc?export=download&id=1PU2feURmuJgnx4mi4O6kYvhXUBpU4Heh
        coreos_image: uc?export=download&id=1w9vheEg1IjD2NP779WtsrjiiOk1TPxpf

        mac_prefix: '00:11:22:33:44'
        bootstrap:
          - "{{ mac_prefix }}:01"

        master:
          - "{{ mac_prefix }}:02"
          - "{{ mac_prefix }}:03"

        worker:
          - "{{ mac_prefix }}:04"
          - "{{ mac_prefix }}:05"

        nginx_host_port: 10.20.26.12:8080
        rhel_download_url: https://docs.google.com/uc?export=download&id=1V2arjbla8oz8A9hdxv0EOqtcelHhxkZ4
        rhel_download_checksum: ""
...
