---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu
    privileged: yes
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
...
